apiVersion: monitor.sysdig.com/v1
kind: PrometheusIntegration
metadata:
  name: etcd
spec:
  type: etcd
  scheme: https
  tls_config:
    insecure_skip_verify: true
    cert_file: /etc/kubernetes/pki/etcd-manager/etcd-clients-ca.crt
    key_file: /etc/kubernetes/pki/etcd-manager/etcd-clients-ca.key
