apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheusintegrationtemplates.monitor.sysdig.com
spec:
  group: monitor.sysdig.com
  names:
    kind: PrometheusIntegrationTemplate
    listKind: PrometheusIntegrationTemplateList
    plural: prometheusintegrationtemplates
    singular: prometheusintegrationtemplate
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              template:
                type: string
    served: true
    storage: true
    subresources:
      status: {}