apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prometheusintegrations.monitor.sysdig.com
spec:
  group: monitor.sysdig.com
  names:
    kind: PrometheusIntegration
    listKind: PrometheusIntegrationList
    plural: prometheusintegrations
    singular: prometheusintegration
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
    served: true
    storage: true
    subresources:
      status: {}