apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prometheusintegrationtemplates.monitor.sysdig.com
spec:
  group: monitor.sysdig.com
  names:
    kind: PrometheusIntegrationTemplate
    listKind: PrometheusIntegrationTemplateList
    plural: prometheusintegrationtemplates
    singular: prometheusintegrationtemplate
  scope: Namespaced
  version: v1
