apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prometheusintegrations.monitor.sysdig.com
spec:
  group: monitor.sysdig.com
  names:
    kind: PrometheusIntegration
    listKind: PrometheusIntegrationList
    plural: prometheusintegrations
    singular: prometheusintegration
  scope: Namespaced
  version: v1
